config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments 
      resources :likes
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.is?(:admin)
      can :manage, :all
    else
      can :destroy, Post, author_id: user.id
      can :destroy, Comment, author_id: user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  scope :update_comments_counter, lambda { |post|
                                    post.update(comments_counter: Comment.all.where("post_id = #{post.id}").count)
                                  }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  scope :update_likes_counter, ->(post) { post.update(likes_counter: Like.all.where("post_id = #{post.id}").count) }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :text, presence: true
  validates :title, length: { in: 0..250 }
  validates :comments_counter, :likes_counter, comparison: { greater_than_or_equal_to: 0 }
  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: :post_id
  has_many :comments, foreign_key: :post_id

  scope :update_user_posts_counter, ->(user) { user.update(posts_counter: user.posts.count) }

  scope :five_recent_comments, lambda { |post|
                                 Comment.all.where("post_id = #{post.id}").order(id: :DESC).includes(:post).limit(5)
                               }

  scope :all_posts_for_a_user, ->(author_id) { Post.all.includes(:author).where("author_id = #{author_id}") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  ROLES = %i[admin default].freeze

  scope :three_recent_posts, ->(user) { user.posts.order(id: :DESC).limit(3) }

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @title = '- Add new comment'
    @comment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def create
    @user = current_user
    post = Post.find(params[:post_id])
    add_comment = @user.comments.new(post_id: post.id, text: comment_params[:text])
    if add_comment.save
      Comment.update_comments_counter(post)
      flash[:success] = 'comment created successfully'
      redirect_to user_post_url(post.author_id, post.id)
    else
      flash.now[:error] = 'Error: comment could not be created'
      render :new, locals: { comment: add_comment }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    post = @user.posts.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.destroy
      Comment.update_comments_counter(post)
      flash[:success] = 'Comment was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to user_post_path(post.author_id, post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    user_post = Post.find(params[:post_id])
    user = User.find(params[:user_id])
    @like = Like.create(author_id: user.id, post_id: user_post.id)
    if @like.save
      Like.update_likes_counter(user_post)
      flash[:success] = 'Your like has been added!'

    else
      flash.now[:error] = 'Like could not be added'
    end
    redirect_to user_post_path(user.id, user_post.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @title = "- #{User.find(params[:user_id]).name}"
    @pagy, @posts = pagy_countless(Post.all_posts_for_a_user(params[:user_id]), link_extra: 'data-remote="true"')
    @comments = ->(post) { Post.five_recent_comments(post) }
    @user = User
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.all.where("post_id = #{params[:id]}")
    @user = User
  end

  def new
    @title = '- Add new post'
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @user = User.find(params[:user_id])
    add_post = @user.posts.new(post_params)
    if add_post.save
      Post.update_user_posts_counter(@user)
      flash[:success] = 'Post created successfully'
      redirect_to user_posts_url
    else
      flash.now[:error] = 'Error: Post could not be created'
      render :new, locals: { post: add_post }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    Comment.all.where(post_id: params[:id]).destroy_all
    Like.all.where(post_id: params[:id]).destroy_all
    if @post.destroy
      Post.update_user_posts_counter(@user)
      flash[:success] = 'Post was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to user_posts_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @title = '- Users'
  end

  def show
    @title = "- #{User.find(params[:id]).name}"
    @user = User.find(params[:id])
    @recent_posts = User.three_recent_posts(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_add_comment.html.erb
<h1>New Comment</h1>
<%= form_with model: Comment.new, url: user_post_comments_path do  |form| %>
  <%= form.label :text %><br>
  <%= form.text_field :text %><br>
  <%= form.submit "Add Comment" %>
<% end %>

app/views/comments/new.html.erb
<%= render "add_comment" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App <%= @title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag  "style.css" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1>New Post</h1>
<%= form_with model: Post.new, url: user_posts_path do  |form| %>
  <%= form.label :title %><br>
  <%= form.text_field :title %><br>
  <%= form.label :text %><br>
  <%= form.text_field :text %><br>
  <%= form.submit "Add Post" %>
<% end %>

app/views/posts/index.html.erb
<%= render "users/user", user: user = @user.find(params[:user_id]) %>
<div class="bio">
<h3>Bio<h3>
<p><%= user.bio %></p>
</div>
  <% @posts.each do |post| %>
    <li>
      <article>
        <h2><%= link_to(post.title, user_post_path(params[:user_id], post.id)) %></h2>
        <p><%= post.text %></p>
        <p>Comments: <%= post.comments_counter || 0 %></p>
        <p>Likes: <%= post.likes_counter || 0 %></p>
        <% comments = @comments.call(post) %>
        <% comments.each do |comment| %>
          <section>
            <p><span><%= @user.find(comment.author_id).name %>: </span><%= comment.text %></p>
            <% if can? :destroy, comment %>
              <%= button_to "Delete Comment", user_post_comment_path(params[:user_id],post.id,comment.id), method: :delete %>
            <% end %>
          </section>
        <% end %>
      </article>
    </li>
  <% end %>
  <%= render "form" %>
<%== pagy_nav(@pagy) %>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<%= render "users/user", user: user = @user.find(params[:user_id]) %>
<article>
  <h2><%= @post.title %> by <%= user.name %></h2>
  <p><%= @post.text %></p>
  <p>Comments: <%= @post.comments_counter || 0 %></p>
  <p>Likes: <%= @post.likes_counter || 0 %></p>
  <% @comments.each do |comment| %>
    <section>
      <p><span><%= @user.find(comment.author_id).name %>: </span><%= comment.text %></p>
      <% if can? :destroy, comment %>
        <%= button_to "Delete Comment", user_post_comment_path(params[:user_id],@post.id,comment.id), method: :delete %>
      <% end %>
    </section>
  <% end %>
</article>
<h2>Add a Like</h2>
<%= form_with model: @like, url: user_post_likes_path(user.id, @post.id) do |f| %>
  <div>
    <%= f.submit "Like" %>
  </div>
<% end %>
<%= link_to('Add comment', new_user_post_comment_path(user.id, @post.id) ) %>
<% if can? :destroy, @post %>
  <%= button_to "Delete Post", user_post_path, method: :delete %>
<% end %>

app/views/users/_user.html.erb
<li class="user-list">
  <% if user.photo %>
    <%= image_tag user.photo, alt:'user picture', class: 'user-picture' %>
  <% end %>
  <div class="user-info-container">
    <h2><%= link_to( user.name , user_path(user.id)) %></h2><br>
    <p class="user-number-of-posts" ><strong>Number of posts:</strong> <%= user.posts_counter  %></p><br>
  </div>
</li>

app/views/users/index.html.erb
<% if current_user %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% end %>
<ul class="users-container">
  <% @users.each do |user| %>
      <%= render "user", user: user %>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render "user", user: @user %>
<div class="bio">
  <h3>Bio<h3>
  <p><%= @user.bio %></p>
</div>
<ul>
  <% @recent_posts.each do |post| %>
    <li>
      <article>
        <h2><%= post.title %></h2>
        <p><%= post.text %></p>
        <p>Comments: <%= post.comments_counter || 0 %></p>
        <p>Likes: <%= post.likes_counter || 0 %></p>
      </article>
    </li>
  <% end %>
</ul>
<%= link_to('See all posts', user_posts_path(@user.id) ) %>